name: Docker Image CI

on:
  push:
    branches: ["master"]

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build Docker Image
        run: docker build . --file Dockerfile -t parker1331/ma-docs-service:latest

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: vittz2021@gmail.com
          password: 3107Vika
      
      - name: Push tag to Docker Hub
        run: doker push parker1331/ma-docs-service:latest


